url: https://www.dyeager.org
markdown: kramdown
permalink: /post/:slug:output_ext
plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
